import time
from abort import *


def intro_screen():

    time.sleep(2)
    print("")
    print("")
    print("")
    print("")
    print("==============================")
    print("         Welcome to")
    print("==============================")
    print("")
    print("")
    print("")
    print("")
    time.sleep(5)
    print("             @@@@@@   @@@@@@ ")
    print("               @@       @@ ")
    print("                 @@   @@  ")
    print("                   @@@ ")
    print("T  H  E  (X)  F  I  L  E  S ")
    print("                   @@@    ")
    print("                 @@   @@ ")
    print("                @@      @@ ")
    print("              @@@@@@  @@@@@@")
    print("")
    print("")
    print("")
    print("")
    print("==============================")
    time.sleep(5)
    print("")
    print("")
    print("")
    print("")
    print("Scully: Mulder?")
    time.sleep(4)
    print("")
    print("Scully: Mulder, können Sie mich hören? Hier ist Scully!")
    time.sleep(3)
    print("")
    print("Scully: Verstehen Sie mich? [J]a oder [N]ein?")
    time.sleep(2)
    print("")
    eingabe = input("Eingabe: ")
    time.sleep(3)
    if eingabe.upper() == "J":
        print("")
        print("")
        print("")
        print("")
        print("Scully: Sehr gut, Mulder!")
        time.sleep(3)
        print("")
        print("Scully: Ihre Mission startet in 5 Sekunden.\n\n Machen Sie sich bereit!")
        time.sleep(5)
    else:
        time.sleep(3)
        print("")
        print("")
        print("")
        print("")
        print(
            "Scully: Ich kann Sie nicht verstehen, Mulder.\n\n Bitte die Eingabe wiederholen!")
        print("Scully: Verstehen Sie mich? [J]a oder [N]ein?")
        eingabe = input("Eingabe: ")
        if eingabe.upper() == "J":
            print("")
            print("")
            print("")
            print("")
            print("Scully: Sehr gut, Mulder!")
            print(
                "Scully: Ihre Mission startet in 5 Sekunden.\n\n Machen Sie sich bereit!")
            time.sleep(5)
        else:
            time.sleep(3)
            print("")
            print("")
            print("")
            print("")
            print(
                "Scully: Ich kann Sie nicht verstehen, Mulder.\n\n Bitte die Eingabe wiederholen!")
            print("Scully: Verstehen Sie mich? [J]a oder [N]ein?")
            eingabe = input("Eingabe: ")
            if eingabe.upper() == "J":
                print("")
                print("")
                print("")
                print("")
                print("Scully: Sehr gut, Mulder!")
                print(
                    "Scully: Ihre Mission startet in 5 Sekunden.\n\n Machen Sie sich bereit!")
                time.sleep(5)
            else:
                time.sleep(3)
                print("")
                print("")
                print("")
                print("")
                print("Scully: Ich kann Sie nicht verstehen, Mulder\n\n Wir müssen die Mission abbrechen.\n Kehren Sie zur Basis zurück!")
                print("")
                print("")
                print("")
                print("")
                print("==============================")
                print("       Spiel beendet!")
                print("==============================")
                time.sleep(5)
                abbrechen()  # funktioniert noch nicht wie gewünscht


def level_1_intro():
    print("")
    print("")
    print("")
    print("")
    print("==============================")
    print("      MISSION GESTARTET")
    print("==============================")
    print("")
    print("")
    print("")
    print("")
    print("Scully: Mulder, Sie befinden sich vor Deck 4 des Raumschiffs.")
    time.sleep(2)
    print("")
    print("Scully: Ich werde Sie aus der Ferne so gut ich kann unterstützen.")
    time.sleep(2)
    print("")
    print("Scully: Gemeinsam werden wir den entführten Hund des Präsidenten Joe Biden aus den Fängen der Aliens befreien!")
    time.sleep(2)
    print("")
    print("Scully: Unsere Sensoren melden, dass sich noch Aliens im Raumschiff befinden.\n Seien Sie vorsichtig, Mulder!")
    time.sleep(2)
    print("")
    print("Scully: Der Hund Donald T. müsste sich, unseren Daten nach, in Raum 4 befinden")
    time.sleep(3.5)
    print("")
    print("Scully: Die Tür vor Ihnen wird sich gleich öffnen. \n\n\n Machen Sie sich bereit!")
    time.sleep(20)
    print("")
    print("Die Tür öffnet sich in: 5 Sekunden")
    time.sleep(1)
    print("Die Tür öffnet sich in: 4 Sekunden")
    time.sleep(1)
    print("Die Tür öffnet sich in: 3 Sekunden")
    time.sleep(1)
    print("Die Tür öffnet sich in: 2 Sekunden")
    time.sleep(1)
    print("Die Tür öffnet sich in: 1 Sekunde")
    time.sleep(1)
    print("")
    print("")
    print("")
    print("")
    print("==============================")
    print("       Tür öffnet sich")
    print("==============================")
    print("")
    print("")
    print("")
    print("")
    time.sleep(3)
